name: Code Checking Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-check:
    runs-on: <link>ubuntu-latest</link>

    steps:
      - name: Checkout code
        uses: <link>actions/checkout</link>@v3

      - name: Set up Node.js 16
        uses: <link>actions/setup-node</link>@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: <link>actions/setup-python</link>@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get latest versions
        id: versions
        run: |
          echo "::set-output name=checkout::$(curl -s https://api.github.com/repos/actions/checkout/releases/latest | jq -r .tag_name)"
          echo "::set-output name=setup_python::$(curl -s https://api.github.com/repos/actions/setup-python/releases/latest | jq -r .tag_name)"

      - name: Compare versions and update workflow
        run: |
          checkout_version=${{ steps.versions.outputs.checkout }}
          setup_python_version=${{ steps.versions.outputs.setup_python }}
          sed -i "s/actions\/checkout@v[^']*/actions\/checkout@$checkout_version/" .github/workflows/code-checking-workflow.yml
          sed -i "s/actions\/setup-python@v[^']*/actions\/setup-python@$setup_python_version/" .github/workflows/code-checking-workflow.yml

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/workflows/code-checking-workflow.yml
          git commit -m "Update GitHub Actions versions"
          git push

      - name: Run linter
        uses: eslint/eslint-action@v3

      - name: Run code formatter
        uses: actions/checkout@v3 # Update the uses field with the correct action reference
        with:
          repository: actions/format
          ref: v3

      - name: Run code analysis
        run: python website_change_detection.py
