name: Code Checking Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "Failed to install some dependencies"

          # Install TensorFlow version 2.8.0, or the latest version if not available
          if ! pip install tensorflow==2.8.0; then
            echo "TensorFlow 2.8.0 not available, installing the latest version"
            pip install tensorflow
          fi || echo "Failed to install TensorFlow"

          # Display the installed TensorFlow version
          python -c "import tensorflow as tf; print('Installed TensorFlow version:', tf.__version__)"

      - name: Get latest versions
        id: versions
        run: |
          echo "checkout=$(curl -s https://api.github.com/repos/actions/checkout/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV
          echo "setup_python=$(curl -s https://api.github.com/repos/actions/setup-python/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV

      - name: Compare versions and update workflow
        run: |
          checkout_version=${{ steps.versions.outputs.checkout }}
          setup_python_version=${{ steps.versions.outputs.setup_python }}
          sed -i "s/actions\/checkout@v[^']*/actions\/checkout@$checkout_version/" .github/workflows/code-checking-workflow.yml
          sed -i "s/actions\/setup-python@v[^']*/actions\/setup-python@$setup_python_version/" .github/workflows/code-checking-workflow.yml

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/workflows/code-checking-workflow.yml
          git commit -m "Update GitHub Actions versions"
          git push

      - name: Run code formatter
        uses: actions/checkout@v3
        with:
          repository: actions/format
          ref: v3

      - name: Run code analysis
        run: python website_change_detection.py
