name: Code Checking Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-check:
    runs-on:
 
ubuntu-latest


    
steps:

      
-
 
name:
 
Checkout
 
code

        
uses:
 
actions/checkout@v3


      
-
 
name:
 
Set
 
up
 
Python

        
uses:
 
actions/setup-python@v3

        
with:

          
python-version:
 
'3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Format code
        uses: pre-commit/action-python-format@v2.8.2

      - name: Run code analysis
        run: python website_change_detection.py
